version: "3.7"

services:
  app:
    image: snaps-dropud-nu
    user: node
    networks:
      - traefik
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.snaps-dropud-nu.rule=Host(`snaps.dropud.nu`)
      - traefik.http.services.snaps-dropud-nu.loadbalancer.server.port=3000

networks:
  traefik:
    external: true
