version: "3"

services:
  app:
    build: .
    user: node
    restart: always
    networks:
      - web
      - default
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=snaps.dropud.nu"
      - "traefik.frontend.rule=Host:snaps.dropud.nu"
      - "traefik.port=8000"
      - "traefik.docker.network=web"
      - "traefik.domain=snaps.dropud.nu"
    container_name: snaps.dropud.nu

networks:
  web:
    external: true
